config/routes.rb
AsciiArt::Application.routes.draw do
  root :to => 'posts#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  resources :users
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :text, :title, :state, :city
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessible :email, :name, :provider, :uid

  def self.create_with_omniauth auth
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to root_url, notice: 'You must be logged in to create new posts'  unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, :except => :index

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      current_user.posts << @post
      if current_user.save!
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Signed in!'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def belongs_to_user? id
    id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AsciiArt
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'shared/header'
    #ascii_art_container
      =render 'shared/notice'
      = yield
    = render 'shared/footer'

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :city
    %br
    = f.text_field :city
  .field
    = f.label :state
    %br
    = f.text_field :state
  .field
    = f.label :text
    %br
    = f.text_area :text
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts
%hr

- @posts.each do |post|
  %h2= post.title

  %p
    %pre
      = post.text

  %p
    %img{:alt => "Static Map of #{post.city}, #{post.state}",
         :src => "http://maps.google.com/maps/api/staticmap?center=#{post.city},#{post.state}&zoom=9&size=300x300&maptype=roadmap&sensor=false"}

  -if current_user && belongs_to_user?(post.user_id)
    %p
      = link_to 'Show', post
      = link_to 'Edit', edit_post_path(post)
      = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @post.title
%p
  %b Text:
  %pre
    = @post.text
  %img{:alt => "Static Map of #{@post.city}, #{@post.state}",
             :src => "http://maps.google.com/maps/api/staticmap?center=#{@post.city},#{@post.state}&zoom=9&size=300x300&maptype=roadmap&sensor=false"}
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path

app/views/shared/_footer.html.haml
#footer

app/views/shared/_header.html.haml
#header
  - if current_user
    Sign in as: #{current_user.name}
    = link_to 'Sign Out', signout_path
    %br
    = link_to 'New Post', new_post_path
  - else
    = link_to 'Sign in with Twitter', '/auth/twitter'
    %br
    = link_to 'Sign in with Facebook', '/auth/facebook'

app/views/shared/_notice.html.haml
#flash-messages
  - if flash[:alert]
    %p.flash-error= flash[:alert]
  - if flash[:notice]
    %p.flash-notice= flash[:notice]